### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [tjgavlick/whiskey-blog-node#1]
from here: https://github.com/tjgavlick/whiskey-blog-node/blob/4fb73762ccb96fa7595da148942147810288ee39/models/post.js#L115

The premise and the implementation are both wrong.

See: https://stackoverflow.com/questions/39805736/get-join-table-as-array-of-results-with-postgresql-nodejs

:wink:

**Comment by tjgavlick** [comment]
Learning more every day! Thanks very much for the input; it's cool how active you are in looking out for your project.

Opted for the single-query method (postgres continues to surprise and delight): https://github.com/tjgavlick/whiskey-blog-node/blob/master/models/post.js#L113

**Comment by vitaly-t** [comment]
>  it's cool how active you are in looking out for your project.

Looking at how people use it tells me about weaknesses in the design.

Next though, get your SQL into external files, see [Query Files](https://github.com/vitaly-t/pg-promise#query-files) and [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo) :wink:

> Opted for the single-query method (postgres continues to surprise and delight): 

Good start! :wink:

**Comment by vitaly-t** [comment]
> pg-promise doesn't seem to recognize dates returned in json,

It is PostgreSQL that works that way, not the client-side library.

You would need to re-cast such columns inside your query, somehow, I'm not even sure how, from the top of my head. Or just convert after getting the values :)

**Comment by tjgavlick** [comment]
> Next though, get your SQL into external files

Done!

> Looking at how people use it tells me about weaknesses in the design.

Well, I am happy to be a data point, though I wouldn't take too much stock in my usage, me being rather new at this
